/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prueba1;

import javax.swing.JOptionPane;

/**
 *
 * @author telip
 */
public class agregarItemWIN extends javax.swing.JFrame {
    BlockBuster bb= new BlockBuster();

    /**
     * Creates new form agregarItemWIN
     */
    
    public agregarItemWIN() {
        initComponents();
        nombreLabel.setVisible(false);
        codigoLabel.setVisible(false);
        altLabel.setVisible(false);
        altComboBox.setVisible(false);
        nombreFIELD.setVisible(false);
        codigoFIELD.setVisible(false);
        jButton3.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreFIELD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoFIELD = new javax.swing.JTextField();
        altComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        altLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        nombreLabel.setText("Nombre:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 74, 34));
        getContentPane().add(nombreFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 222, 34));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel2.setText("Tipo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 74, 34));

        codigoLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        codigoLabel.setText("Codigo:");
        getContentPane().add(codigoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 74, 34));
        getContentPane().add(codigoFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 222, 34));

        altComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playstation", "Xbox", "Wii" }));
        getContentPane().add(altComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 34));

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 102, 35));

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jButton2.setText("Elegir Tipo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 113, 35));

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 113, 35));

        altLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        altLabel.setText("Consola:");
        getContentPane().add(altLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 34));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie", "Game" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 222, 34));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new mainMenuWIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String tipo=jComboBox2.getSelectedItem().toString();
        
       nombreLabel.setVisible(true);
            codigoLabel.setVisible(true);
            nombreFIELD.setVisible(true);
            codigoFIELD.setVisible(true);
            jButton3.setVisible(true);
            
       if(tipo.equals("Game")){
           altComboBox.setVisible(true);
           altLabel.setVisible(true);

       }else{
           altComboBox.setVisible(false);
           altLabel.setVisible(false);
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String tipo=jComboBox2.getSelectedItem().toString();
      String nombre=nombreFIELD.getText();
      int codigo= Integer.parseInt(codigoFIELD.getText());
      String consola=altComboBox.getSelectedItem().toString();
      
      if(bb.buscarItem(codigo, tipo)==null){
         bb.agregarItem(codigo, nombre, tipo);
      JOptionPane.showMessageDialog(null, "Item agregado exitosamente");
      }else{
          JOptionPane.showMessageDialog(null,"Ya existe ese codigo");
      }
      
      
      
      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarItemWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarItemWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarItemWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarItemWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarItemWIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> altComboBox;
    private javax.swing.JLabel altLabel;
    private javax.swing.JTextField codigoFIELD;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreFIELD;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
